test: set test using Patch to be async: false (#368)
There is a failing test on main, I think it's because we're using Patch
on a test with `async: true`, while Patch is incompatible with async
tests

```elixir
1) test in_context?/2 can detect behaviours (Forge.Ast.EnvTest)
Error:      test/forge/ast/env_test.exs:181
     ** (UndefinedFunctionError) function Patch.Mock.Delegate.For.Forge.Ast.Parser.Spitfire.string_to_quoted/1 is undefined (module Patch.Mock.Delegate.For.Forge.Ast.Parser.Spitfire is not available)
     code: env = new_env("@behaviour Modul|e")
     stacktrace:
       Patch.Mock.Delegate.For.Forge.Ast.Parser.Spitfire.string_to_quoted("@behaviour Module")
       (forge 0.1.0) lib/forge/ast.ex:173: Forge.Ast.from/1
       (forge 0.1.0) lib/forge/ast.ex:123: Forge.Ast.analyze/1
       test/forge/ast/env_test.exs:14: Forge.Ast.EnvTest.new_env/2
       test/forge/ast/env_test.exs:182: (test)
```